const base = '/ggs-photos'

export const images = {
  logo: `${base}/gss logo.png`,
  hero: `${base}/ggs-photo (1).jpeg`,
  schoolBuilding: `${base}/ggs-photo (2).jpeg`,
  students: `${base}/ggs-photo (3).jpeg`,
  classroom: `${base}/ggs-photo (4).jpeg`,
  sports: `${base}/ggs-photo (5).jpeg`,
  graduation: `${base}/ggs-photo (6).jpeg`,
  event: `${base}/ggs-photo (7).jpeg`,
  learning: `${base}/ggs-photo (8).jpeg`,
  campus: `${base}/ggs-photo (9).jpeg`,
  music: `${base}/ggs-photo (10).jpeg`,
  science: `${base}/ggs-photo (11).jpeg`,
  group: `${base}/ggs-photo (12).jpeg`,
  awards: `${base}/ggs-photo (13).jpeg`,
  outdoor: `${base}/ggs-photo (14).jpeg`,
  library: `${base}/ggs-photo (15).jpeg`,
  art: `${base}/ggs-photo (16).jpeg`,
  competition: `${base}/ggs-photo (17).jpeg`,
  leadership: `${base}/ggs-photo (18).jpeg`,
  community: `${base}/ggs-photo (19).jpeg`,
  swimming: `${base}/ggs-photo (20).jpeg`,
  basketball: `${base}/ggs-photo (21).jpeg`,
  debate: `${base}/ggs-photo (22).jpeg`,
  computer: `${base}/ggs-photo (23).jpeg`,
  drama: `${base}/ggs-photo (24).jpeg`,
  graduation2: `${base}/ggs-photo (25).jpeg`,
  teachers: `${base}/ggs-photo (26).jpeg`,
  campus2: `${base}/ggs-photo (27).jpeg`,
  scienceFair: `${base}/ggs-photo (28).jpeg`,
  sportsDay: `${base}/ggs-photo (29).jpeg`,
  musicFestival: `${base}/ggs-photo (30).jpeg`,
  enrollment: `${base}/ggs-photo (31).jpeg`,
  treePlanting: `${base}/ggs-photo (32).jpeg`,
  ceremony: `${base}/ggs-photo (33).jpeg`,
  lab: `${base}/ggs-photo (34).jpeg`,
}
